logging:
  file: macbot.log
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
models:
  llm:
    context_length: 8192
    max_tokens: 200
    path: models/llama.cpp/models/Qwen_Qwen3-4B-Instruct-2507-Q4_K_M.gguf
    server_url: http://localhost:8080/v1/chat/completions
    temperature: 0.4
    threads: -1
  stt:
    bin: models/whisper.cpp/build/bin/whisper-cli
    language: en
    model: models/whisper.cpp/models/ggml-base.en.bin
  tts:
    piper:
      voice_path: /Users/admin/Downloads/MacBot/piper_voices/en_US-lessac-medium/model.onnx
    speed: 1.0
    voice: en_US-lessac-medium
performance:
  cpu_limit_percent: 80
  max_concurrent_requests: 3
  memory_limit_mb: 4096
prompts:
  system: 'You are MacBot, a helpful AI assistant running locally on macOS.

    You have access to various tools and can help with tasks on this computer.

    Always be concise and helpful in your responses.

    '
  tool_use: 'When using tools, be concise and provide clear instructions.

    Explain what you''re doing and why.

    '
services:
  orchestrator:
    auto_restart: true
    check_interval: 10
  rag_server:
    api_tokens:
    - change-me
    collection_name: macbot_docs
    data_dir: rag_data
    host: localhost
    port: 8001
    rate_limit_per_minute: 60
  web_dashboard:
    host: 0.0.0.0
    port: 3000
tools:
  app_launcher:
    allowed_apps:
    - Safari
    - Terminal
    - Finder
    - Mail
    - Messages
    - FaceTime
    - Photos
    - Music
    - Calendar
    - Notes
    - Calculator
  enabled:
  - web_search
  - screenshot
  - app_launcher
  - system_monitor
  - weather
  - rag_search
  rag_search:
    max_results: 5
    similarity_threshold: 0.7
  screenshot:
    format: png
    save_path: ~/Desktop
  system_monitor:
    update_interval: 5
  weather:
    default_location: ''
  web_search:
    default_engine: google
    timeout: 10
voice_assistant:
  block_sec: 0.03
  interruption:
    context_buffer_size: 10
    conversation_timeout: 30
    enabled: true
    interrupt_cooldown: 0.5
    interrupt_threshold: 0.01
  microphone_device: 0
  sample_rate: 16000
  silence_hang: 0.6
  speaker_device: 0
  vad_threshold: 0.005
  wake_word: hey macbot
